// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: referrals.sql

package dbs

import (
	"context"
)

const referralsNew = `-- name: ReferralsNew :exec
INSERT INTO referrals (referee_user_id, referrer_user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type ReferralsNewParams struct {
	RefereeUserID  int64
	ReferrerUserID int64
}

func (q *Queries) ReferralsNew(ctx context.Context, arg ReferralsNewParams) error {
	_, err := q.exec(ctx, q.referralsNewStmt, referralsNew, arg.RefereeUserID, arg.ReferrerUserID)
	return err
}
