// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package dbs

import (
	"time"
)

type ProfileHourlyViewsStat struct {
	Time   time.Time
	UserID int64
	Count  int64
}

type ProfileTotalView struct {
	UserID int64
	Count  int64
}

type User struct {
	ID int64
}
