// Code generated by qtc from "sitemap_github_profiles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSitemapGithubProfile(qw422016 *qt422016.Writer, users []ProfileView) {
	qw422016.N().S(`
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    `)
	for _, user := range users {
		qw422016.N().S(`
        <url>
            <loc>`)
		qw422016.E().S(user.Username)
		qw422016.N().S(`</loc>
        </url>
    `)
	}
	qw422016.N().S(`
</urlset>
`)
}

func WriteSitemapGithubProfile(qq422016 qtio422016.Writer, users []ProfileView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSitemapGithubProfile(qw422016, users)
	qt422016.ReleaseWriter(qw422016)
}

func SitemapGithubProfile(users []ProfileView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSitemapGithubProfile(qb422016, users)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
