// Code generated by qtc from "badge.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamBadge(qw422016 *qt422016.Writer, stats ProfileViewsStats) {
	qw422016.N().S(`
<svg width="568" height="24" viewBox="0 0 568 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <g>
    <rect width="113" height="24" rx="4" fill="#24292F"></rect>
    <rect x="112" width="54" height="24" rx="4" fill="#6D96FF"></rect>
    <rect x="112" width="1" height="24" fill="#E4EAF1"></rect>
    <g
      fill="#fff"
      text-anchor="middle"
      font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
      font-size="14"
    >
      <text x="57.5" y="16">Views per day</text>
      <text x="138" y="16">`)
	qw422016.N().DL(stats.DayCount)
	qw422016.N().S(`</text>
    </g>
  </g>
  <g>
    <rect x="171" width="82" height="24" rx="4" fill="#24292F"></rect>
    <rect x="252" width="54" height="24" rx="4" fill="#6D96FF"></rect>
    <rect x="252" width="1" height="24" fill="#E4EAF1"></rect>
    <g
      fill="#fff"
      text-anchor="middle"
      font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
      font-size="14"
    >
      <text x="213" y="16">per week</text>
      <text x="279" y="16">`)
	qw422016.N().DL(stats.WeekCount)
	qw422016.N().S(`</text>
    </g>
  </g>

  <g>
    <rect x="311" width="90" height="24" rx="4" fill="#24292F"></rect>
    <rect x="400" width="54" height="24" rx="4" fill="#6D96FF"></rect>
    <rect x="400" width="1" height="24" fill="#E4EAF1"></rect>
    <g
      fill="#fff"
      text-anchor="middle"
      font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
      font-size="14"
    >
      <text x="356" y="16">per month</text>
      <text x="427" y="16">`)
	qw422016.N().DL(stats.MonthCount)
	qw422016.N().S(`</text>
    </g>
  </g>
  <g>
    <rect x="459" width="54" height="24" rx="4" fill="#24292F"></rect>
    <rect x="512" width="54" height="24" rx="4" fill="#6D96FF"></rect>
    <rect x="512" width="1" height="24" fill="#E4EAF1"></rect>
    <g
      fill="#fff"
      text-anchor="middle"
      font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
      font-size="14"
    >
      <text x="485" y="16">total</text>
      <text x="539" y="16">`)
	qw422016.N().DL(stats.TotalCount)
	qw422016.N().S(`</text>
    </g>
  </g>
</svg>
`)
}

func WriteBadge(qq422016 qtio422016.Writer, stats ProfileViewsStats) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamBadge(qw422016, stats)
	qt422016.ReleaseWriter(qw422016)
}

func Badge(stats ProfileViewsStats) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteBadge(qb422016, stats)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
