// Code generated by qtc from "redirect.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRawRedirect(qw422016 *qt422016.Writer, url string) {
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
	Redirect...
	<script>window.location.replace("`)
	qw422016.E().S(url)
	qw422016.N().S(`")</script>
</body>
</html>
`)
}

func WriteRawRedirect(qq422016 qtio422016.Writer, url string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRawRedirect(qw422016, url)
	qt422016.ReleaseWriter(qw422016)
}

func RawRedirect(url string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRawRedirect(qb422016, url)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
