// Code generated by qtc from "charity.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/v2/charity.qtpl:1
package v2

//line internal/templates/v2/charity.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/v2/charity.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/v2/charity.qtpl:1
func streamcharity(qw422016 *qt422016.Writer) {
//line internal/templates/v2/charity.qtpl:1
	qw422016.N().S(`
<figure class="hero__figure-donate">
	<img
		src="/assets/images/come-back-alive-ukraine.png"
		alt="Make a donation to our charity fund – Come Back Alive"
	/>
	<figcaption class="hero__figcaption">
		«Come Back Alive» is Ukraine's largest charitable organization.
		The Foundation implements projects that save our defenders'
		lives and help them liberate the Ukrainian land from invaders.
	</figcaption>
</figure>
<button class="hero__donate-button">
	<a href="https://savelife.in.ua/en/donate-en/" class="hero__donate-link">Donate</a>
</button>
`)
//line internal/templates/v2/charity.qtpl:16
}

//line internal/templates/v2/charity.qtpl:16
func writecharity(qq422016 qtio422016.Writer) {
//line internal/templates/v2/charity.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/charity.qtpl:16
	streamcharity(qw422016)
//line internal/templates/v2/charity.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/charity.qtpl:16
}

//line internal/templates/v2/charity.qtpl:16
func charity() string {
//line internal/templates/v2/charity.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/charity.qtpl:16
	writecharity(qb422016)
//line internal/templates/v2/charity.qtpl:16
	qs422016 := string(qb422016.B)
//line internal/templates/v2/charity.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/charity.qtpl:16
	return qs422016
//line internal/templates/v2/charity.qtpl:16
}
