// Code generated by qtc from "charity.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamcharity(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<figure class="hero__figure-donate">
	<img
		src="/assets/images/come-back-alive-ukraine.png"
		alt="Make a donation to our charity fund – Come Back Alive"
	/>
	<figcaption class="hero__figcaption">
		«Come Back Alive» is Ukraine's largest charitable organization.
		The Foundation implements projects that save our defenders'
		lives and help them liberate the Ukrainian land from invaders.
	</figcaption>
</figure>
<button class="hero__donate-button">
	<a href="https://savelife.in.ua/en/donate-en/" class="hero__donate-link">Donate</a>
</button>
`)
}

func writecharity(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamcharity(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func charity() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writecharity(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
