// Code generated by qtc from "djinni.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamdjinni(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<figure class="hero__figure-donate">
	<img
		src="/assets/images/djinni.png"
		alt="Anonymous job search for developers – Djinni"
	/>
	<figcaption class="hero__figcaption">
		Anonymous job search for developers and everyone working in tech.
	</figcaption>
</figure>
<button class="hero__donate-button">
	<a href="https://djinni.co/signup?lang=en&from=u8" class="hero__donate-link">Sign up</a>
</button>
`)
}

func writedjinni(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamdjinni(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func djinni() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writedjinni(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
