// Code generated by qtc from "djinni.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamdjinni(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<figure class="hero__figure-donate">
	<img
		src="/assets/images/djinni.jpeg"
		alt="Anonymous job search for developers – Djinni"
	/>
	<figcaption class="hero__figcaption">
		`)
	if djinniTextLongOrShort() {
		qw422016.N().S(`
			Looking for a job? Try anonymous job search: you create a profile, recruiters reach out to you, and you share your contacts only with those you like.
		`)
	} else {
		qw422016.N().S(`
			Anonymous job search for developers and everyone working in tech.
		`)
	}
	qw422016.N().S(`
	</figcaption>
</figure>
<button class="hero__donate-button">
	`)
	if djinniButtonSignUpOrJobs() {
		qw422016.N().S(`
		<a href="https://djinni.co/jobs?lang=en&from=u8" class="hero__donate-link">Browse jobs</a>
	`)
	} else {
		qw422016.N().S(`
		<a href="https://djinni.co/signup?lang=en&from=u8" class="hero__donate-link">Sign up</a>
	`)
	}
	qw422016.N().S(`
</button>
`)
}

func writedjinni(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamdjinni(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func djinni() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writedjinni(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
