// Code generated by qtc from "favicon.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/v2/favicon.qtpl:1
package v2

//line internal/templates/v2/favicon.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/v2/favicon.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/v2/favicon.qtpl:1
func streamfavicon(qw422016 *qt422016.Writer) {
//line internal/templates/v2/favicon.qtpl:1
	qw422016.N().S(`
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <meta property="og:image" content="/assets/images/anastasiia-sihetii-designer-1200x630.png">
`)
//line internal/templates/v2/favicon.qtpl:20
}

//line internal/templates/v2/favicon.qtpl:20
func writefavicon(qq422016 qtio422016.Writer) {
//line internal/templates/v2/favicon.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/favicon.qtpl:20
	streamfavicon(qw422016)
//line internal/templates/v2/favicon.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/favicon.qtpl:20
}

//line internal/templates/v2/favicon.qtpl:20
func favicon() string {
//line internal/templates/v2/favicon.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/favicon.qtpl:20
	writefavicon(qb422016)
//line internal/templates/v2/favicon.qtpl:20
	qs422016 := string(qb422016.B)
//line internal/templates/v2/favicon.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/favicon.qtpl:20
	return qs422016
//line internal/templates/v2/favicon.qtpl:20
}
