// Code generated by qtc from "header.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/v2/header.qtpl:1
package v2

//line internal/templates/v2/header.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/v2/header.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/v2/header.qtpl:1
func streamheader(qw422016 *qt422016.Writer, currentPageProfile ProfileView, sessionProfile ProfileView) {
//line internal/templates/v2/header.qtpl:1
	qw422016.N().S(`
    `)
//line internal/templates/v2/header.qtpl:2
	if sessionProfile.ID == 0 {
//line internal/templates/v2/header.qtpl:2
		qw422016.N().S(`
        `)
//line internal/templates/v2/header.qtpl:3
		streamunauthorizedHeader(qw422016, currentPageProfile)
//line internal/templates/v2/header.qtpl:3
		qw422016.N().S(`
    `)
//line internal/templates/v2/header.qtpl:4
	} else {
//line internal/templates/v2/header.qtpl:4
		qw422016.N().S(`
        `)
//line internal/templates/v2/header.qtpl:5
		streamauthorizedHeader(qw422016, sessionProfile)
//line internal/templates/v2/header.qtpl:5
		qw422016.N().S(`
    `)
//line internal/templates/v2/header.qtpl:6
	}
//line internal/templates/v2/header.qtpl:6
	qw422016.N().S(`
`)
//line internal/templates/v2/header.qtpl:7
}

//line internal/templates/v2/header.qtpl:7
func writeheader(qq422016 qtio422016.Writer, currentPageProfile ProfileView, sessionProfile ProfileView) {
//line internal/templates/v2/header.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/header.qtpl:7
	streamheader(qw422016, currentPageProfile, sessionProfile)
//line internal/templates/v2/header.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/header.qtpl:7
}

//line internal/templates/v2/header.qtpl:7
func header(currentPageProfile ProfileView, sessionProfile ProfileView) string {
//line internal/templates/v2/header.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/header.qtpl:7
	writeheader(qb422016, currentPageProfile, sessionProfile)
//line internal/templates/v2/header.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/templates/v2/header.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/header.qtpl:7
	return qs422016
//line internal/templates/v2/header.qtpl:7
}

//line internal/templates/v2/header.qtpl:9
func streamunauthorizedHeader(qw422016 *qt422016.Writer, currentPageProfile ProfileView) {
//line internal/templates/v2/header.qtpl:9
	qw422016.N().S(`
<header class="header">
    <div class="header__wrapper wrapper-u8">
        <a href="/" class="header__logo">
            <img class="header__logo-img" src="/assets/images/logo.svg" alt="logo">
        </a>
        <div class="header__stars">
            <iframe src="https://ghbtns.com/github-btn.html?user=u8views&repo=go-u8views&type=star&count=true&size=large"
                    frameborder="0" scrolling="0" width="170" height="30" title="GitHub"></iframe>
        </div>
        <button class="button__log-in">
            <a href="/login/github?referrer=`)
//line internal/templates/v2/header.qtpl:20
	qw422016.N().DL(currentPageProfile.ID)
//line internal/templates/v2/header.qtpl:20
	qw422016.N().S(`" class="button__link">
                <img
                        src="/assets/images/github.svg"
                        width="24"
                        height="24"
                        alt="github"
                        class="button__log-in-img"
                />
                <span class="button__text">Log in with GitHub</span>
            </a>
        </button>
    </div>
</header>
`)
//line internal/templates/v2/header.qtpl:33
}

//line internal/templates/v2/header.qtpl:33
func writeunauthorizedHeader(qq422016 qtio422016.Writer, currentPageProfile ProfileView) {
//line internal/templates/v2/header.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/header.qtpl:33
	streamunauthorizedHeader(qw422016, currentPageProfile)
//line internal/templates/v2/header.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/header.qtpl:33
}

//line internal/templates/v2/header.qtpl:33
func unauthorizedHeader(currentPageProfile ProfileView) string {
//line internal/templates/v2/header.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/header.qtpl:33
	writeunauthorizedHeader(qb422016, currentPageProfile)
//line internal/templates/v2/header.qtpl:33
	qs422016 := string(qb422016.B)
//line internal/templates/v2/header.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/header.qtpl:33
	return qs422016
//line internal/templates/v2/header.qtpl:33
}

//line internal/templates/v2/header.qtpl:35
func streamauthorizedHeader(qw422016 *qt422016.Writer, sessionProfile ProfileView) {
//line internal/templates/v2/header.qtpl:35
	qw422016.N().S(`
<header class="header">
    <div class="header__wrapper auth wrapper-u8">
        <a href="/" class="header__logo">
            <img class="header__logo-img" src="/assets/images/logo.svg" alt="logo">
        </a>
        <div class="header__stars">
            <iframe src="https://ghbtns.com/github-btn.html?user=u8views&repo=go-u8views&type=star&count=true&size=large"
                    frameborder="0" scrolling="0" width="170" height="30" title="GitHub"></iframe>
        </div>
        <div class="header__profile">
            <button class="header__profile-button">
                <img src="https://avatars.githubusercontent.com/u/`)
//line internal/templates/v2/header.qtpl:47
	qw422016.E().S(sessionProfile.SocialProviderUserID)
//line internal/templates/v2/header.qtpl:47
	qw422016.N().S(`?v=4&s=48"
                     width="48" height="48" alt="`)
//line internal/templates/v2/header.qtpl:48
	qw422016.E().S(sessionProfile.GetName())
//line internal/templates/v2/header.qtpl:48
	qw422016.N().S(` profile photo">
            </button>
            <div class="header__modal modal">
                <div class="modal__profile">
                    <img src="https://avatars.githubusercontent.com/u/`)
//line internal/templates/v2/header.qtpl:52
	qw422016.E().S(sessionProfile.SocialProviderUserID)
//line internal/templates/v2/header.qtpl:52
	qw422016.N().S(`?v=4&s=48"
                         class="modal__user-photo" width="48" height="48"
                         alt="`)
//line internal/templates/v2/header.qtpl:54
	qw422016.E().S(sessionProfile.GetName())
//line internal/templates/v2/header.qtpl:54
	qw422016.N().S(` profile photo">
                    <div class="modal__profile-info">
                        <div class="modal__profile-name">`)
//line internal/templates/v2/header.qtpl:56
	qw422016.E().S(sessionProfile.GetName())
//line internal/templates/v2/header.qtpl:56
	qw422016.N().S(`</div>
                        <a href="https://u8views.com/github/`)
//line internal/templates/v2/header.qtpl:57
	qw422016.E().S(sessionProfile.Username)
//line internal/templates/v2/header.qtpl:57
	qw422016.N().S(`" class="modal__link">
                            <img src="/assets/images/u8-icon.svg" width="24" height="24" alt="link">
                            <span class="modal__profile-u8views">u8views.com/github/`)
//line internal/templates/v2/header.qtpl:59
	qw422016.E().S(sessionProfile.Username)
//line internal/templates/v2/header.qtpl:59
	qw422016.N().S(`</span>
                        </a>
                        <a href="https://github.com/`)
//line internal/templates/v2/header.qtpl:61
	qw422016.E().S(sessionProfile.Username)
//line internal/templates/v2/header.qtpl:61
	qw422016.N().S(`" class="modal__link">
                            <img src="/assets/images/github.svg" width="24" height="24" alt="link">
                            <span class="modal__profile-github">github.com/`)
//line internal/templates/v2/header.qtpl:63
	qw422016.E().S(sessionProfile.Username)
//line internal/templates/v2/header.qtpl:63
	qw422016.N().S(`</span>
                        </a>
                    </div>
                </div>
                <div class="modal__log-out">
                    <a href="/logout" class="modal__button">
                        <img src="/assets/images/log-out.svg" alt="log-out">
                        <span>Log out</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

<script>
    document.querySelector(".header__profile-button").addEventListener("click", () => {
        document.querySelector(".header__modal").classList.toggle("active");
    })
</script>
`)
//line internal/templates/v2/header.qtpl:83
}

//line internal/templates/v2/header.qtpl:83
func writeauthorizedHeader(qq422016 qtio422016.Writer, sessionProfile ProfileView) {
//line internal/templates/v2/header.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/header.qtpl:83
	streamauthorizedHeader(qw422016, sessionProfile)
//line internal/templates/v2/header.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/header.qtpl:83
}

//line internal/templates/v2/header.qtpl:83
func authorizedHeader(sessionProfile ProfileView) string {
//line internal/templates/v2/header.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/header.qtpl:83
	writeauthorizedHeader(qb422016, sessionProfile)
//line internal/templates/v2/header.qtpl:83
	qs422016 := string(qb422016.B)
//line internal/templates/v2/header.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/header.qtpl:83
	return qs422016
//line internal/templates/v2/header.qtpl:83
}
