// Code generated by qtc from "plausible_analytics.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamplausibleAnalytics(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<script defer data-domain="u8views.com" src="https://plausible.io/js/script.js"></script>
`)
}

func writeplausibleAnalytics(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamplausibleAnalytics(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func plausibleAnalytics() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeplausibleAnalytics(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
