// Code generated by qtc from "sitemap_github_profiles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSitemapGithubProfiles(qw422016 *qt422016.Writer, usernames []string) {
	qw422016.N().S(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
`)
	for _, username := range usernames {
		qw422016.N().S(`        <url>
            <loc>https://u8views.com/github/`)
		qw422016.E().S(username)
		qw422016.N().S(`</loc>
        </url>
`)
	}
	qw422016.N().S(`</urlset>
`)
}

func WriteSitemapGithubProfiles(qq422016 qtio422016.Writer, usernames []string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSitemapGithubProfiles(qw422016, usernames)
	qt422016.ReleaseWriter(qw422016)
}

func SitemapGithubProfiles(usernames []string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSitemapGithubProfiles(qb422016, usernames)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
