// Code generated by qtc from "sitemap_github_profiles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/v2/sitemap_github_profiles.qtpl:1
package v2

//line internal/templates/v2/sitemap_github_profiles.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/v2/sitemap_github_profiles.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/v2/sitemap_github_profiles.qtpl:1
func StreamSitemapGithubProfiles(qw422016 *qt422016.Writer, usernames []string) {
//line internal/templates/v2/sitemap_github_profiles.qtpl:1
	qw422016.N().S(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
`)
//line internal/templates/v2/sitemap_github_profiles.qtpl:4
	for _, username := range usernames {
//line internal/templates/v2/sitemap_github_profiles.qtpl:4
		qw422016.N().S(`        <url>
            <loc>https://u8views.com/github/`)
//line internal/templates/v2/sitemap_github_profiles.qtpl:6
		qw422016.E().S(username)
//line internal/templates/v2/sitemap_github_profiles.qtpl:6
		qw422016.N().S(`</loc>
        </url>
`)
//line internal/templates/v2/sitemap_github_profiles.qtpl:8
	}
//line internal/templates/v2/sitemap_github_profiles.qtpl:8
	qw422016.N().S(`</urlset>
`)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
}

//line internal/templates/v2/sitemap_github_profiles.qtpl:10
func WriteSitemapGithubProfiles(qq422016 qtio422016.Writer, usernames []string) {
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	StreamSitemapGithubProfiles(qw422016, usernames)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
}

//line internal/templates/v2/sitemap_github_profiles.qtpl:10
func SitemapGithubProfiles(usernames []string) string {
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	WriteSitemapGithubProfiles(qb422016, usernames)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	qs422016 := string(qb422016.B)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
	return qs422016
//line internal/templates/v2/sitemap_github_profiles.qtpl:10
}
