// Code generated by qtc from "total_badge.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v2

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamTotalBadge(qw422016 *qt422016.Writer, stats ProfileViewsStats) {
	qw422016.N().S(`
<svg width="568" height="24" viewBox="0 0 568 24" fill="none" xmlns="http://www.w3.org/2000/svg">
 <g>
     <rect x="171" width="82" height="24" rx="4" fill="#24292F"></rect>
     <rect x="252" width="54" height="24" rx="4" fill="#6D96FF"></rect>
     <rect x="252" width="1" height="24" fill="#E4EAF1"></rect>
     <g
       fill="#fff"
       text-anchor="middle"
       font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
       font-size="14"
     >
       <text x="213" y="16">Total views</text>
       <text x="279" y="16">`)
	qw422016.N().DL(stats.TotalCount)
	qw422016.N().S(`</text>
     </g>
   </g>
</svg>
`)
}

func WriteTotalBadge(qq422016 qtio422016.Writer, stats ProfileViewsStats) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamTotalBadge(qw422016, stats)
	qt422016.ReleaseWriter(qw422016)
}

func TotalBadge(stats ProfileViewsStats) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteTotalBadge(qb422016, stats)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
