---
- name: "Git clone u8views"
  hosts: "web"
  gather_facts: "no"
  vars:
    - REPOSITORY: "https://github.com/u8views/go-u8views.git"
    - DESTINATION: "/var/go/u8views"

  tasks:
    - name: "Ensure directory {{ DESTINATION }} exists"
      ansible.builtin.file:
        path: "{{ DESTINATION }}"
        state: "directory"

    - name: "Git pull repository {{ REPOSITORY }}"
      ansible.builtin.git:
        repo: "{{ REPOSITORY }}"
        version: "main"
        dest: "{{ DESTINATION }}"
