---
# https://fabianlee.org/2021/02/03/ansible-cloning-a-git-repository-that-requires-credentials/
- name: "Git clone u8views"
  hosts: web
  gather_facts: no

  tasks:
    - name: "/var/go/u8views"
      file:
        path: /var/go/u8views
        state: directory

    - name: "git pull"
      ansible.builtin.git:
        repo: https://github.com/u8views/go-u8views.git
        version: main
        dest: /var/go/u8views

    - name: "git status"
      shell: "git status"
      args:
        chdir: "/var/go/u8views"
      register: out
      when: false
    - debug:
        var: out.stdout_lines
      when: false

    - name: "ls -la"
      shell: "ls -la"
      args:
        chdir: "/var/go/u8views"
      register: out
      when: false
    - debug:
        var: out.stdout_lines
      when: false
