---
- name: "Make"
  hosts: web
  gather_facts: no
  vars_prompt:
    - name: command
      private: no

  tasks:
    - name: "Make exists"
      apt:
        name:
          - "make"
        state: present

    - name: "make --makefile=Makefile.server {{ command }}"
      make:
        chdir: "/var/go/u8views"
        target: "{{ command }}"
      register: out
    - debug:
        var: out.stdout_lines
